# Batch deployment: directory layout, manifest, SLURM array-job generation/submission,
# and a `:local` process backend (used for testing and small batches).
#
# Batch directory layout:
#   <dir>/batch.toml        manifest (everything needed to re-load the batch later)
#   <dir>/params.json       the parameter sets (one JSON object per task)
#   <dir>/setup.jl          copy of the user's problem-setup script
#   <dir>/runtask.jl        generated worker entry script
#   <dir>/job.sbatch        generated SLURM array-job submission script (slurm backend)
#   <dir>/tasks/            per-task results: task_NNNNNN.json (+ .h5), .done/.failed markers
#   <dir>/logs/             SLURM / worker logs

"""
    SlurmConfig(; kwargs...)

SLURM submission options for [`deploy_batch`](@ref).

- `time`, `partition`, `mem`, `cpus_per_task`, `gres`: standard `#SBATCH` options
  (empty/`nothing` values are omitted).
- `max_concurrent`: throttle for the array job (`--array=1-N%max_concurrent`).
- `julia`: the `julia` executable to use on the cluster (default `"julia"`).
- `project`: Julia project to activate on the workers. Defaults to the deploying
  session's active project — appropriate when the cluster shares the filesystem.
  Set it to the path of the project on the cluster otherwise.
- `julia_flags`: extra flags for the worker `julia` invocation (e.g. `["-t","4"]`).
- `sbatch_args`: extra raw arguments appended to the `sbatch` call.
- `ssh`: if set (e.g. `"user@login.cluster"`), the batch directory is rsync'ed to
  `remote_dir` on that host, `sbatch` runs over ssh, and `gather_batch`/`batch_status`
  fetch results back over ssh. When `nothing` (default), the batch directory itself is
  assumed to live on a filesystem shared with the compute nodes.
- `remote_dir`: remote path of the batch directory (ssh mode only).
"""
Base.@kwdef struct SlurmConfig
    time::String = "1:00:00"
    partition::String = ""
    mem::String = ""
    cpus_per_task::Int = 1
    gres::String = ""
    max_concurrent::Int = 0
    julia::String = "julia"
    project::String = abspath(Base.active_project())
    julia_flags::Vector{String} = String[]
    sbatch_args::Vector{String} = String[]
    ssh::Union{Nothing,String} = nothing
    remote_dir::Union{Nothing,String} = nothing
end

"""
In-memory handle for a deployed (or re-loaded) batch of mode simulations. All state
lives in the batch directory, so a `BatchInfo` can be re-created in a new Julia session
with [`load_batch`](@ref).
"""
struct BatchInfo
    dir::String
    manifest::Dict{String,Any}
    params::Vector{NamedTuple}
end

Base.length(b::BatchInfo) = length(b.params)
n_tasks(b::BatchInfo) = length(b.params)
_taskdir(b::BatchInfo) = joinpath(b.dir, "tasks")
_task_id_str(i::Int) = @sprintf("%06i", i)
_task_base(b::BatchInfo, i::Int) = joinpath(_taskdir(b), "task_" * _task_id_str(i))

function Base.show(io::IO, b::BatchInfo)
    print(io, "BatchInfo(\"", get(b.manifest, "name", "?"), "\", ", length(b.params),
        " tasks, backend=", get(b.manifest, "backend", "?"), ", dir=", b.dir, ")")
end

# ---------------------------------------------------------------------------------
# script generation
# ---------------------------------------------------------------------------------

function _runtask_script()
    return """
    # Worker entry point (generated by ModeSweeps): runs one task of a batch.
    #   julia --project=<project> runtask.jl <batchdir> <task index>
    using ModeSweeps
    ModeSweeps.run_task(ARGS[1], parse(Int, ARGS[2]))
    """
end

function _sbatch_script(name::String, n::Int, cfg::SlurmConfig, batchdir_on_cluster::String)
    lines = String[
        "#!/bin/bash",
        "#SBATCH --job-name=$(name)",
        "#SBATCH --output=$(joinpath(batchdir_on_cluster, "logs", "slurm-%A_%a.out"))",
        "#SBATCH --array=1-$(n)" * (cfg.max_concurrent > 0 ? "%$(cfg.max_concurrent)" : ""),
        "#SBATCH --time=$(cfg.time)",
        "#SBATCH --cpus-per-task=$(cfg.cpus_per_task)",
    ]
    isempty(cfg.partition) || push!(lines, "#SBATCH --partition=$(cfg.partition)")
    isempty(cfg.mem) || push!(lines, "#SBATCH --mem=$(cfg.mem)")
    isempty(cfg.gres) || push!(lines, "#SBATCH --gres=$(cfg.gres)")
    flags = join(cfg.julia_flags, " ")
    push!(lines, "")
    push!(lines, "$(cfg.julia) --project=$(cfg.project) $(flags) " *
                 "$(joinpath(batchdir_on_cluster, "runtask.jl")) $(batchdir_on_cluster) \$SLURM_ARRAY_TASK_ID")
    return join(lines, "\n") * "\n"
end

# ---------------------------------------------------------------------------------
# deployment
# ---------------------------------------------------------------------------------

"""
    deploy_batch(setup_file, params; name, dir, kwargs...) -> BatchInfo

Deploy a batch of mode simulations, one task per parameter set in `params` (a
`Vector` of `NamedTuple`s, e.g. from [`param_grid`](@ref), or a `NamedTuple` of
scalar/vector values which is expanded with `param_grid`).

`setup_file` is a Julia script defining the problem for one parameter set. It is copied
into the batch directory and `include`d by each worker, and must define

    make_problem(p::NamedTuple) -> (; ε⁻¹, ∂ε_∂ω, grid [, ∂²ε_∂ω², n₂])

mapping a parameter set to the smoothed inverse dielectric tensor, its frequency
derivative(s) and the spatial grid. By convention `p.ω` is the optical frequency.
If the problem additionally supplies a Kerr-coefficient map `n₂` (μm²/W, e.g. from
`DielectricSmoothing.smooth_scalar`) and the parameter set an optical power `p.P`
(W), each task performs a first-order power-corrected solve (`solve_k_kerr`) —
making power sweeps just another batch parameter (`param_grid(ω=…, P=…)`). The
script must contain the `using` statements it needs (the worker runs it inside a fresh
module with the OptiMode component packages already loaded).

Keyword options:

- `name`: batch name (defaults to a timestamped name).
- `dir`: batch directory (created; defaults to `./modesweeps_<name>`). All batch state
  lives here, enabling [`load_batch`](@ref)`(dir)` in later Julia sessions.
- `nev=1`: number of bands per task.
- `save_fields=false`: when `true`, workers additionally store full mode-field data
  (eigenvectors and E-fields) per task in HDF5; when `false` only the lightweight
  summary (effective & group index, GVD, effective area, polarization) is produced.
- `solver="KrylovKitEigsolve()"`: an expression string constructing the eigensolver on
  the worker (e.g. `"GPUSolver(Float32)"` for the CUDA backend).
- `solver_kwargs=(;)`: keyword arguments forwarded to `solve_k` (e.g. `k_tol`).
- `backend=:slurm`: `:slurm` submits a SLURM array job per `slurm::SlurmConfig`;
  `:local` runs the same per-task worker script in local background processes (useful
  for testing and small batches); `:none` only writes the batch directory (inspect or
  submit `job.sbatch` manually).
- `slurm=SlurmConfig()`: SLURM/worker configuration (also supplies the worker `julia`
  and project for the `:local` backend).
- `submit=true`: set `false` for a dry run (alias for `backend=:none`).
"""
function deploy_batch(setup_file::AbstractString, params; name::AbstractString="",
    dir::AbstractString="", nev::Int=1, save_fields::Bool=false,
    solver::AbstractString="KrylovKitEigsolve()", solver_kwargs::NamedTuple=(;),
    backend::Symbol=:slurm, slurm::SlurmConfig=SlurmConfig(), submit::Bool=true)

    params_v = _normalize_params(params)
    isempty(params_v) && throw(ArgumentError("empty parameter list"))
    isfile(setup_file) || throw(ArgumentError("setup file not found: $setup_file"))
    name = isempty(name) ? "modesweep_" * Dates.format(now(), "yyyymmdd_HHMMSS") : String(name)
    dir = abspath(isempty(dir) ? joinpath(pwd(), "modesweeps_" * name) : String(dir))
    submit || (backend = :none)

    mkpath(dir)
    mkpath(joinpath(dir, "tasks"))
    mkpath(joinpath(dir, "logs"))
    cp(setup_file, joinpath(dir, "setup.jl"); force=true)
    write(joinpath(dir, "params.json"), _params_to_json(params_v))
    Serialization.serialize(joinpath(dir, "params.jls"), params_v)  # exact-typed copy
    write(joinpath(dir, "runtask.jl"), _runtask_script())

    batchdir_on_cluster = isnothing(slurm.ssh) ? dir : something(slurm.remote_dir,
        throw(ArgumentError("SlurmConfig: `remote_dir` is required when `ssh` is set")))
    write(joinpath(dir, "job.sbatch"), _sbatch_script(name, length(params_v), slurm, batchdir_on_cluster))

    manifest = Dict{String,Any}(
        "name" => name,
        "created" => string(now()),
        "n_tasks" => length(params_v),
        "nev" => nev,
        "save_fields" => save_fields,
        "solver" => String(solver),
        "solver_kwargs" => Dict(String(k) => v for (k, v) in pairs(solver_kwargs)),
        "backend" => String(backend),
        "julia" => slurm.julia,
        "project" => slurm.project,
        "julia_flags" => slurm.julia_flags,
        "ssh" => something(slurm.ssh, ""),
        "remote_dir" => something(slurm.remote_dir, ""),
        "slurm_jobid" => "",
        "param_keys" => String.(collect(keys(first(params_v)))),
    )
    _write_manifest(dir, manifest)

    batch = BatchInfo(dir, manifest, params_v)
    if backend === :slurm
        _submit_slurm!(batch, slurm)
    elseif backend === :local
        _submit_local!(batch, slurm)
    elseif backend === :none
        @info "Batch written (not submitted). Submit later with `sbatch $(joinpath(dir, "job.sbatch"))`." dir
    else
        throw(ArgumentError("unknown backend :$backend (expected :slurm, :local or :none)"))
    end
    return batch
end

_write_manifest(dir, manifest) = open(joinpath(dir, "batch.toml"), "w") do io
    TOML.print(io, manifest)
end

"ssh-aware command wrapper: run `cmdvec` locally or on the configured remote host"
function _remote_cmd(ssh::AbstractString, cmdvec::Vector{String})
    return `ssh $ssh $(join(cmdvec, " "))`
end

function _submit_slurm!(batch::BatchInfo, cfg::SlurmConfig)
    script = joinpath(batch.dir, "job.sbatch")
    out = if isnothing(cfg.ssh)
        Sys.which("sbatch") === nothing && error(
            "`sbatch` not found on this machine. Use `SlurmConfig(ssh=..., remote_dir=...)` " *
            "to submit to a remote cluster, or backend=:local / :none.")
        read(`sbatch $(cfg.sbatch_args) $script`, String)
    else
        remote = cfg.remote_dir
        run(`ssh $(cfg.ssh) mkdir -p $remote`)
        run(`rsync -a $(batch.dir)/ $(cfg.ssh):$remote/`)
        read(_remote_cmd(cfg.ssh, vcat(["sbatch"], cfg.sbatch_args, [joinpath(remote, "job.sbatch")])), String)
    end
    m = match(r"Submitted batch job (\d+)", out)
    jobid = m === nothing ? "" : String(m.captures[1])
    batch.manifest["slurm_jobid"] = jobid
    _write_manifest(batch.dir, batch.manifest)
    @info "Submitted SLURM array job" jobid n_tasks = length(batch) dir = batch.dir
    return batch
end

function _submit_local!(batch::BatchInfo, cfg::SlurmConfig)
    runtask = joinpath(batch.dir, "runtask.jl")
    for i in 1:length(batch)
        log = joinpath(batch.dir, "logs", "local-$( _task_id_str(i) ).out")
        cmd = `$(cfg.julia) --project=$(cfg.project) $(cfg.julia_flags) $runtask $(batch.dir) $i`
        run(pipeline(cmd; stdout=log, stderr=log); wait=false)
    end
    @info "Launched $(length(batch)) local worker processes" dir = batch.dir
    return batch
end

"""
    load_batch(dir) -> BatchInfo

Re-load a previously deployed batch from its directory (works in a fresh Julia
session; everything needed is stored in `batch.toml` and `params.json` at deployment
time). Results can then be inspected with [`batch_status`](@ref) and collected with
[`gather_batch`](@ref) — including partial results of a still-running batch.
"""
function load_batch(dir::AbstractString)
    dir = abspath(dir)
    manifest = TOML.parsefile(joinpath(dir, "batch.toml"))
    params = try
        # exact-typed copy (same Julia/package versions); fall back to portable JSON
        Vector{NamedTuple}(Serialization.deserialize(joinpath(dir, "params.jls")))
    catch
        _params_from_json(read(joinpath(dir, "params.json"), String))
    end
    return BatchInfo(dir, manifest, params)
end

"""
    cancel_batch(batch)

Cancel the SLURM array job of a deployed batch (`scancel`, over ssh when configured).
"""
function cancel_batch(batch::BatchInfo)
    jobid = get(batch.manifest, "slurm_jobid", "")
    isempty(jobid) && (@warn "batch has no recorded SLURM job id"; return nothing)
    ssh = get(batch.manifest, "ssh", "")
    if isempty(ssh)
        run(`scancel $jobid`)
    else
        run(_remote_cmd(ssh, ["scancel", jobid]))
    end
    return nothing
end

"""
    frequency_sweep(setup_file; ω, name="freq_sweep", kwargs...) -> BatchInfo

Convenience wrapper around [`deploy_batch`](@ref) for parallelized frequency sweeps,
optionally combined with sweeps of geometric/material parameters: any additional
keyword whose value is a vector is swept (Cartesian product, with `ω` varying fastest);
scalars are held fixed and passed through to every task.

    frequency_sweep("my_setup.jl"; ω = 0.55:0.005:0.75, w_top = [1.4, 1.7], T = 30.0,
                    nev = 2, backend = :slurm, slurm = SlurmConfig(time="0:30:00"))

Deployment options (`nev`, `save_fields`, `solver`, `solver_kwargs`, `backend`,
`slurm`, `name`, `dir`, `submit`) are split off automatically; all other keywords
become sweep parameters.
"""
function frequency_sweep(setup_file::AbstractString; ω, name::AbstractString="freq_sweep",
    dir::AbstractString="", nev::Int=1, save_fields::Bool=false,
    solver::AbstractString="KrylovKitEigsolve()", solver_kwargs::NamedTuple=(;),
    backend::Symbol=:slurm, slurm::SlurmConfig=SlurmConfig(), submit::Bool=true, params...)
    grid_params = param_grid(; ω=ω, params...)
    return deploy_batch(setup_file, grid_params; name, dir, nev, save_fields, solver,
        solver_kwargs, backend, slurm, submit)
end
